### ISSUE TITLE
The logic for when a user is not staff & wants to share editing on their post doesn't work

### ISSUE THREAD

**Issue by nogweii** [gnunicorn/discourse-plugin-shared-edit#1]
Just installed your plugin but my users couldn't see the share edit button. I had to change the conditional in `assets/javascripts/shared_edit_menu.js` to:

```
  if ((current_user && current_user.staff) || post.yours) {
```

**Comment by nogweii** [comment]
Though this is inverted logic from the original condition as I found it easier that way. `buffer.push` is called within the condition, instead of returning.

**Comment by gnunicorn** [comment]
hey @evaryont, you've got a pull-request for me about this?

**Comment by nogweii** [comment]
I don't have one right now, trying to fix a broken discourse instance
(whoopsie in a plugin I'm writing) and don't have the time presently.
