### ISSUE TITLE
Is not working with 1.2.0.beta8	

### ISSUE THREAD

**Issue by terraboss** [gnunicorn/discourse-plugin-shared-edit#4]
Discourse is not loading posts anymore. By removing the plugin, everything just works fine. 

What's the reason for that?

**Comment by wrong7** [comment]
I have the same issue

**Comment by saintsal** [comment]
Hey Benjamin, long time!  Same issue for me running v1.5.0.beta12 +125

**Comment by gnunicorn** [comment]
I am sorry but I am not maintaining any discourse related code any more. I am happy to hand this over to anyone, who wants to update and continue to maintain it, but I am not anymore.

Sorry.
